Modify docker files to auto-detect arch for SG

diff --git a/Replicator/tests/data/docker/sg/Dockerfile b/Replicator/tests/data/docker/sg/Dockerfile
--- a/Replicator/tests/data/docker/sg/Dockerfile
+++ b/Replicator/tests/data/docker/sg/Dockerfile
@@ -1,12 +1,53 @@
+# FROM ubuntu:22.04
+
+# ARG SG_DEB
+# ARG SSL=true
+# ARG LEGACY_MODE=false
+
+# RUN [ -z "$SG_DEB" ] && echo "SG_DEB is required" && exit 1 || true
+
+# ADD $SG_DEB /opt/sg/couchbase-sync-gateway.deb
+
+# COPY cert /opt/sg/cert
+# COPY config /opt/sg/config
+# COPY scripts /opt/sg/scripts
+
+# WORKDIR /opt/sg
+
+# RUN apt -yqq update 
+# RUN apt -yqq install systemctl curl
+# RUN apt -yqq install ./couchbase-sync-gateway.deb
+
+# EXPOSE 4984
+# EXPOSE 4985
+
+# ENV SSL=${SSL}
+# ENV LEGACY_MODE=${LEGACY_MODE}
+
+# CMD ./scripts/start.sh ${SSL} ${LEGACY_MODE}
+
 FROM ubuntu:22.04
 
-ARG SG_DEB
+ARG SG_DEB_ARM64
+ARG SG_DEB_AMD64
 ARG SSL=true
 ARG LEGACY_MODE=false
 
-RUN [ -z "$SG_DEB" ] && echo "SG_DEB is required" && exit 1 || true
+RUN [ -z "$SG_DEB_ARM64" ] && echo "SG_DEB_ARM64 is required" && exit 1 || true
+RUN [ -z "$SG_DEB_AMD64" ] && echo "SG_DEB_AMD64 is required" && exit 1 || true
 
-ADD $SG_DEB /opt/sg/couchbase-sync-gateway.deb
+RUN apt -yqq update 
+RUN apt -yqq install curl
+
+RUN ARCHITECTURE="$(dpkg --print-architecture)" && \
+    if [ "$ARCHITECTURE" = "amd64" ]; then \
+        curl -o couchbase-sync-gateway.deb $SG_DEB_AMD64; \
+    elif [ "$ARCHITECTURE" = "arm64" ]; then \
+        curl -o couchbase-sync-gateway.deb $SG_DEB_ARM64; \
+    else \
+        echo "Unsupported architecture"; \
+        exit 1; \
+    fi
 
 COPY cert /opt/sg/cert
 COPY config /opt/sg/config
@@ -14,9 +55,8 @@ COPY scripts /opt/sg/scripts
 
 WORKDIR /opt/sg
 
-RUN apt -yqq update 
-RUN apt -yqq install systemctl curl
-RUN apt -yqq install ./couchbase-sync-gateway.deb
+RUN apt -yqq install systemctl
+RUN dpkg -i ./couchbase-sync-gateway.deb
 
 EXPOSE 4984
 EXPOSE 4985
